When a request fails with an invalid FileMaker token, try to repeat t…
soliantconsulting/fm-data-api-client pull request #6
Opened 2021-01-20 15:03 UTC by DASPRiD

…he request with a new token

2021-02-24 18:19 UTC, lart2150 requested changes
I tested this and it clears the session but returns a promise instead of the result from the second call.

2021-02-24 18:19 UTC, lart2150 commented on src/Client.ts
> +                return this.request(path, request, false);
This needs an await

2021-02-24 19:38 UTC, lart2150 commented on src/Client.ts
> +                return this.request(path, request, false);
I was wrong his his needing an await we need to do something like
request.headers.delete('Authorization'); before we call request a second time.

2022-04-17 11:54 UTC, DASPRiD commented
This has been addressed in https://github.com/soliantconsulting/fm-data-api-client/commit/ef9b348ab7273e4c7a7b60840bb4a141d1557b43.

2022-04-17 11:54 UTC, closed without merging